name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: >
          This issue has been automatically marked as stale because it has not had recent activity for 30 days. 
          If you believe this issue is still relevant, please comment or interact with it to keep it open. 
        stale-pr-message: >
          This pull request has been automatically marked as stale because it has not had recent activity for 30 days. 
          If you believe this pull request is still relevant, please comment or interact with it to keep it open. 
        days-before-stale: 30
        remove-stale-when-updated: true
        stale-issue-label: stale
        exempt-issue-labels: "pinned,security,note"
        stale-pr-label: stale
        exempt-pr-labels: "work-in-progress"
